@baseURL = http://localhost:3001
@jwtToken={{logInUser.response.body.accessToken}}

@postUuid = {{createPostOwned.response.body.id}}
@postSlug = {{createPostOwned.response.body.slug}}
@imagePath = {{uploadImage.response.body.url}}
@imageUrl = {{baseURL}}{{imagePath}}

@userNameForTesting=Gabriel
@userEmailForTesting=gabriel@email.com
@userPasswordForTesting=123456
@userNewPasswordForTesting=123456

# AUTH ############################

### authLogin
# @name logInUser
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123456"
}

# USER ############################

### get an user
# @name ReadOneUser
GET {{baseURL}}/user/1234
Authorization: Bearer {{jwtToken}}

### create an user
# @name createUser
POST {{baseURL}}/user
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123456",
  "name":"teste da silva"
}

### update an user
# @name updateUser
PATCH {{baseURL}}/user/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "email": "teste@teste.com",
  "password": "123456",
  "name":"teste da silva"
}

### update user password
# @name updateUserPassword
PATCH {{baseURL}}/user/me/password
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword":"123456",
  "newPassword":"123456"
}

### read one user
# @name readOneUser
GET {{baseURL}}/user/me
Authorization: Bearer {{jwtToken}}

### delete one user
# @name readOneUser
DELETE {{baseURL}}/user/me
Authorization: Bearer {{jwtToken}}

# POST ############################

### create a post
# @name createPostOwned
POST {{baseURL}}/post/me
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title":"post title",
  "excerpt":"Excerto",
  "content":"post content"
}

### read all public posts
# @name readAllPostPublic
GET {{baseURL}}/post

### read one public post
# @name readOnePostPublic
GET {{baseURL}}/post/{{postSlug}}

### read one post owned
# @name readOnePostOwned
GET {{baseURL}}/post/me/{{postUuid}}
Authorization: Bearer {{jwtToken}}

### read all post owned
# @name readAllPostOwned
GET {{baseURL}}/post/me
Authorization: Bearer {{jwtToken}}

### create a post
# @name updateOnePostOwned
PATCH {{baseURL}}/post/me/{{postUuid}}
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title":"post title",
  "excerpt":"Excerto",
  "content":"post content",
  "published":true
}

### delete one post owned
# @name DeleteOnePostOwned
DELETE {{baseURL}}/post/me/{{postUuid}}
Authorization: Bearer {{jwtToken}}

# UPLOAD ################################################

### Upload Image
# @name uploadImage
POST {{baseURL}}/upload
Authorization: Bearer {{jwtToken}}
Content-Type: multipart/form-data; boundary=----BryenFormBoundary

------BryenFormBoundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

../dev/images/image.png
------BryenFormBoundary--


### Read Image
# @name readImage
GET {{imageUrl}}


####################################

