@baseURL = http://localhost:3000


### authLogin
# @name logInUser
POST {{baseURL}}/auth/login
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "123"
}

### get an user
# @name ReadOneUser
GET {{baseURL}}/user/1234

### create an user
# @name createUser
POST {{baseURL}}/user
Content-Type: application/json

{
  "email": "teste@teste.com",
  "password": "1245",
  "name":"teste da silva"
}
